-- 코드를 입력하세요
SELECT
    ub.TITLE,
    ur.BOARD_ID,
    ur.REPLY_ID,
    ur.WRITER_ID,
    ur.CONTENTS,
    ur.CREATED_DATE
FROM USED_GOODS_BOARD ub JOIN USED_GOODS_REPLY ur
ON ub.BOARD_ID = ur.BOARD_ID
WHERE ub.CREATED_DATE LIKE '2022-10%'
ORDER BY CREATED_DATE ASC, TITLE ASC